package http

import (
	"github.com/mgjules/tic-tac-toe/game"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/mgjules/tic-tac-toe/docs" // docs is generated by Swag CLI
)

// Routes setups the http routes
func (s *Server) Routes(gameRepository game.Repository, host, port string) {
	// Health-check
	s.Router.GET("/", s.HandleHealthCheck())

	// Move
	s.Router.POST("/move", s.HandleMove(gameRepository))

	// Swagger
	url := ginSwagger.URL("http://" + host + ":" + port + "/swagger/doc.json")
	s.Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// NotFound
	s.Router.NoRoute(s.HandleNotFound())
}
